sudo: required
services:
  - docker

before_install:
  - docker build -t mercedesgm/docker-flow -f Dockerfile.dev .

script:
  - docker run -e CI=true mercedesgm/docker-flow npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-flow"
  env: "DockerFlow-env"
  bucket_name: "elasticbeanstalk-us-east-1-475828484100"
  bucket_path: "docker-flow"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
