#docker build -f Dockerfile.dev .
#docker run -p 3000:3000 -v /app/node_modules -v $(pwd):/app ID_GOES_HERE
FROM node:alpine

WORKDIR './app'

COPY package.json .

RUN npm install

COPY . .

CMD ["npm", "run", "start"]